services:
  opencsv-test:
    image: opencsv-test:latest
    mem_limit: 256m
    cpu_shares: 1024
    depends_on:
      - postgres
    ports:
      - 8080:8080
  postgres:
    image: postgres:12.20-alpine3.20
#    mem_limit: 512m
    cpu_shares: 1024
    restart: always
    ports:
      - 5432:5432  
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
  pgadmin4:
    image: dpage/pgadmin4:2024-09-16-1
    restart: always
    depends_on:
      - postgres
    ports:
      - 8778:80    
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password    
