spring:
  application.name: opencsv-test
  servlet:
    multipart.max-file-size: -1
    multipart.max-request-size: -1

metrics.instance-id: ${spring.application.name}-${random.int(10)}
postgres:
  host: "localhost"
  data-source-name: "opencsv-test-spring-app"
  db-name: "admin"
  max-connections: 2
  user: "admin"
  password: "password"
  ssl: false
  application-name: "opencsv-test-spring-app"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
      instance: ${metrics.instance-id}
      host: ${HOSTNAME}
      namespace: default
  otlp:
    metrics:
      export:
#        url: http://0:4318/v1/metrics
        url: http://otel-collector:4318/v1/metrics
#        headers:
#          x-app: ${spring.application.name}
        step: 5s
        resourceAttributes:
          host: ${HOSTNAME}
          application: ${spring.application.name}
          instance:  ${metrics.instance-id}
          namespace: default