spring:
  application:
    name: oauth2-web
  security:
    oauth2:
      client:
        registration:
          local:
            client-id: 1078677407703-gcee2fcd1toj2vd89ao4ci8q5qf9m160.apps.googleusercontent.com
            client-secret: xxx
            client-authentication-method: client_secret_jwt
            authorization-grant-type: client_credentials
        provider:
          local:
#            token-uri: https://www.googleapis.com/oauth2/v4/token
            token-uri: http://localhost:9090/oauth2/v4/token

logging:
  level:
    root: info
    org.springframework.security: debug
