server:
  port: 9090
spring:
  application:
    name: oauth2-web
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-client
            client-secret: 0hDZjbiqA9wSmXmWIr7wn95dT1GbyihW
            client-authentication-method: client_secret_post
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:8080/realms/master/protocol/openid-connect/token

logging:
  level:
    root: info
    org.springframework: info