spring:
  application:
    name: commons-togglz

mongo:
  application-name: ${spring.application.name}
  collection-name: "features"
  instances:
    - localhost:27017

database:
  name: "commons_togglz"
  table: "features"

core:
  features:
    - "com.commons.togglz.feature.NissanFeatures"
    - "com.commons.togglz.feature.TestFeature"
    - "com.commons.togglz.feature.ToyotaFeatures"

togglz:
  enabled: true
  console:
    enabled: true
    path: /togglz-console
    secured: false