spring:
  application:
    name: commons-togglz

mongo:
  application-name: ${spring.application.name}
  collection-name: "features"
  connection-string: mongodb://localhost:27017/

database:
  name: "commons_togglz"
  table: "features"

togglz:
  enabled: true
  console:
    enabled: true
    path: /togglz-console
    secured: false